### ISSUE TITLE
Bloco "govbr/collapse-label"

### ISSUE THREAD

**Issue by dannielmacedo** [IBICT/wp-govbr-tema#5]
Estou recebendo a mensagem abaixo ao adicionar um bloco Collapse. Como resolver?

> Seu site não oferece suporte para o bloco "govbr/collapse-label". Você pode deixar esse bloco como está ou removê-lo totalmente.

No rodapé também aparece esse problema, o menu aparece como código html.

**Comment by mateuswetah** [comment]
Olá @djsmacedo, tudo bem?

Eu não estou conseguindo reproduzir este erro aqui... testei em uma instalação nova, enviando o [tema](https://github.com/IBICT/wp-govbr-tema/releases/download/v0.1.0/govbr.zip) para a pasta de Temas. Ao acessar os modelos onde este bloco é usado (como o rodapé, onde bloco está sendo carregado), tudo parece ok. 

Este tipo de erro aponta que a função de registro do bloco não foi encontrado, mas o bloco é ativado no próprio tema. Você tem certeza que o tema está instalado e ativo? Se sim, consegue nos fornecer mais detalhes (sua versão do WordPress, ou até um link para testarmos)?

**Comment by dannielmacedo** [comment]
No [site](https://www.ci.ufpb.br/lavid2/) aparece normal, só no editor que dá o problema...  Certamente algo da instalação do Wordpress, alguma restrição que colocaram por aqui, não sei explicar. O font awesome também aparece como html no editor. Em todo caso agradeço demais a atenção.
